#!/usr/bin/env bash
jekyll build && chmod -R a+r _site/ && rsync -apvvz --delete _site/ reflowst@reflowster.com:~/homeautomaton.com/
ssh -t reflowst@reflowster.com 'chmod -R o-w /home/reflowst/homeautomaton.com/; chmod -R g-w /home/reflowst/homeautomaton.com/'
